server:
  port: 8763   #eureka的默认端口

spring:
  application:
    name: eureka-server   #因为是集群，应用名称不能修改


eureka:
  client:
    service-url:
      defaultZone: http://host01:8761/eureka,http://host02:8762/eureka

  instance: #实例的配置
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port} #主机名称：应用名:端口
    hostname: host03
    prefer-ip-address: true #以IP的形式显示具体的服务信息
    lease-renewal-interval-in-seconds: 5  #服务实例的续约的时间间隔