server:
  port: 8081

spring:
  application:
    name: provider


eureka:
  client: #客户端相关配置
    service-url: #指定注册地址
      defaultZone: http://54.250.188.224:8761/eureka
    register-with-eureka: true #可以配置false 意味着不往eureka-server注册
    fetch-registry: true #应用是否去拉去服务列表到本地
    registry-fetch-interval-seconds: 10 #拉去服务列表的间隔时间

  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port} #主机名称：应用名:端口
    prefer-ip-address: true #以IP的形式显示具体的服务信息
    lease-renewal-interval-in-seconds: 5  #服务实例的续约的时间间隔